### ISSUE TITLE
Error when running within Flask application

### ISSUE THREAD

**Issue by bb78657** [marrow/mongo#54]
Im using Flask_Script to run Flask on a localserver.

I am unclear what is causing the error below. 

error trace when run the app though manager
```
if __name__ == '__main__':
    manager.run()

Traceback (most recent call last):
  File "/pathto/myapp/manage.py", line 154, in <module>
    manager.run()
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/flask_script/commands.py", line 425, in __call__
    **self.server_options)
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/werkzeug/serving.py", line 706, in run_simple
    reloader_type)
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/werkzeug/_reloader.py", line 263, in run_with_reloader
    reloader.run()
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/werkzeug/_reloader.py", line 144, in run
    self.extra_files):
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/werkzeug/_reloader.py", line 22, in _iter_module_files
    filename = getattr(module, '__file__', None)
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/marrow/mongo/util/__init__.py", line 62, in __getattr__
    self.__dict__[name] = load(name, self._namespace)
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/marrow/package/loader.py", line 81, in load
    raise LookupError('Unknown plugin "' + target + '"; found: ' + ', '.join(allowable))
LookupError: Unknown plugin "__file__"; found: Polygon, Point, GeoJSONCoord, GeometryCollection, Document, GeoJSON, MultiPoint, MultiLineString, LineString, MultiPolygon
```
I can run unit tests fine (eg see below) indicating the issue is related to code execution during the flask_script manager.runserver() command

```
    def test_password_setter(self):
        user_role = Permission.USER
        u = User(email='user@gmail.com', role=user_role)
        u.password='password'
        self.assertTrue(u.password_hash is not None)
```
marrow User object
```

from marrow.mongo import Index
#here is where the error is initiated when running thouth manage.runserver()
from marrow.mongo.field import Array, Boolean, Date, Integer, Number, ObjectId, Reference, String, Timestamp 
from marrow.mongo.trait import Queryable

class User(Queryable, UserMixin):
    __collection__ = 'user'
    confirmed = Boolean(default=False)
    first_name = String()
    last_name = String()
    email = String()
    password_hash = String()
    #using reference makes updates and queries too complicated
    role = String(choices=[Permission.USER, Permission.MANAGER, Permission.ADMINISTRATOR], default=Permission.USER)
    created = Timestamp()
    revised_on = Date()
    _email = Index('email', unique=True)

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['ADMIN_EMAIL']:
                role = Permission.ADMINISTRATOR
            if self.role is None:
                #default
                self.role = Permission.USER

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

def _create_collection_and_drop():
    assert mongo.db is not None
    #beware, will remove all data from collections
    db = mongo.db
    User.bind(db)
    User.create_collection(drop=True)
```

As a test, Flask starts fine when I change the loader.load() method to:

```
	if namespace and ':' not in target:
		allowable = dict((i.name,  i) for i in iter_entry_points(namespace))
		if target not in allowable:
			if target == '__file__':
				return None
			else:
				raise LookupError('Unknown plugin "' + target + '"; found: ' + ', '.join(allowable))
```

**Comment by amcgregor** [comment]
It does not appear that Werkzeug's reloader is compatible with marrow.mongo. Specifically, Marrow Mongo populates two "virtual namespace packages" (`marrow.mongo.field`, `marrow.mongo.document`) which are not actually real on-disk packages (no `__init__.py` for them). Because they are not backed by on-disk files, those virtual modules do not have a `__file__` attribute, which Werkzeug can't handle.

**Comment by j-solis** [comment]
This is happening in the latest django for me

**Comment by amcgregor** [comment]
Closing as insufficient information is provided to reproduce.

```
LookupError: Unknown plugin "__file__"…
```

This is not an attribute access that occurs under my installation, and the Python version in question is now quite old. Feel free to re-open if reproducible under Python 3.8 or newer and without "live reloading" enabled.

```
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/werkzeug/_reloader.py", line 263, in run_with_reloader
    reloader.run()
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/werkzeug/_reloader.py", line 144, in run
    self.extra_files):
  File "/home/user/.virtualenvs/myapp/lib/python3.5/site-packages/werkzeug/_reloader.py", line 22, in _iter_module_files
    filename = getattr(module, '__file__', None)
```

This segment of traceback clearly implicates the "live reloading" functionality. Python, as a language, **does not have this as a feature**. I always recommend use of an external file monitoring and process management tool, such as [entr](http://eradman.com/entrproject/). (I use this for all of my "watch files and do" needs, such as SCSS recompilation, development web service restarting, browser tab reloading, &c.)
